services:
  example-frontend:
    image: example-frontend # already built from 1.14/example-frontend
    ports:
      - 127.0.0.1:3000:5000

  example-backend:
    image: example-backend # already built from 1.14/example-backend
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:alpine3.21
